# ============================================================
# Sample: extends pipeline
# ============================================================
# Demonstrates the `extends:` keyword.
# Debug this file to see:
#   - The Call Stack showing [extends] base-pipeline.yml
#   - Parameters passed through the extends block
#   - Nested template calls inside the base template
#     (base-pipeline.yml includes build-steps.yml → 3 frames)
# ============================================================

trigger:
  - main

extends:
  template: templates/base-pipeline.yml
  parameters:
    buildConfiguration: Release
    testProjects: '**/UnitTests.csproj'
